export default function Disclaimer() {
  return (
    <footer className="py-12 px-6 bg-stone-950 border-t border-stone-900">
      <div className="max-w-5xl mx-auto">
        {/* Disclaimer */}
        <div className="text-center mb-8">
          <p className="text-sm text-bronze-200/60 leading-relaxed max-w-3xl mx-auto">
            <strong className="text-bronze-200/80">Disclaimer:</strong> This tool provides preliminary analysis for informational purposes only and does not constitute legal advice. The analysis is generated by AI and may contain errors. Consult qualified legal counsel before executing any fund documents. Strategic Fund Partners is not a law firm.
          </p>
        </div>

        {/* Footer links */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 text-sm text-bronze-200/60">
          <a
            href="https://strategicfundpartners.com"
            className="hover:text-bronze-400 transition-colors"
          >
            © {new Date().getFullYear()} Strategic Fund Partners
          </a>
          <span className="hidden sm:inline">•</span>
          <a
            href="https://strategicfundpartners.com/privacy"
            className="hover:text-bronze-400 transition-colors"
          >
            Privacy Policy
          </a>
          <span className="hidden sm:inline">•</span>
          <a
            href="https://strategicfundpartners.com/contact"
            className="hover:text-bronze-400 transition-colors"
          >
            Contact
          </a>
        </div>
      </div>
    </footer>
  );
}
